// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD93z5Tq7SusF2K7CYgbXdlnF5DnRcmjlA',
    appId: '1:140319445760:web:860df7d81f9708cb6e99e5',
    messagingSenderId: '140319445760',
    projectId: 'flicknova-app',
    authDomain: 'flicknova-app.firebaseapp.com',
    storageBucket: 'flicknova-app.firebasestorage.app',
    measurementId: 'G-3SJKMTWF4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVD1gdftQN8KVxiWMppDCADUL0pq1Xmw',
    appId: '1:140319445760:android:aca30db3569ae3896e99e5',
    messagingSenderId: '140319445760',
    projectId: 'flicknova-app',
    storageBucket: 'flicknova-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3pSpvJQ_srgAdJZaA2LWp4TIAZnpSPSs',
    appId: '1:140319445760:ios:b68386b34a71204c6e99e5',
    messagingSenderId: '140319445760',
    projectId: 'flicknova-app',
    storageBucket: 'flicknova-app.firebasestorage.app',
    iosBundleId: 'com.ephraimlabs.flicknova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3pSpvJQ_srgAdJZaA2LWp4TIAZnpSPSs',
    appId: '1:140319445760:ios:b68386b34a71204c6e99e5',
    messagingSenderId: '140319445760',
    projectId: 'flicknova-app',
    storageBucket: 'flicknova-app.firebasestorage.app',
    iosBundleId: 'com.ephraimlabs.flicknova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD93z5Tq7SusF2K7CYgbXdlnF5DnRcmjlA',
    appId: '1:140319445760:web:3e95ff3410a171306e99e5',
    messagingSenderId: '140319445760',
    projectId: 'flicknova-app',
    authDomain: 'flicknova-app.firebaseapp.com',
    storageBucket: 'flicknova-app.firebasestorage.app',
    measurementId: 'G-51CP7HVGMD',
  );

}